spring.application.name=Auth-Service

server.port=4005

spring.datasource.url=jdbc:postgresql://localhost:5433;databaseName=users;trustServerCertificate=true;
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username= ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true