spring.application.name=patient service

spring.datasource.url=jdbc:postgresql://localhost:5432;databaseName=<database_name>;trustServerCertificate=true;
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username= ${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Redis
spring.data.redis.host=${SPRING_REDIS_HOST}
spring.data.redis.port=6379
spring.data.redis.password=${SPRING_REDIS_PASSWORD}

# Server
server.port=4000

# Logging
logging.level.org.springframework=INFO

billing.service.address=${BILLING_SERVICE_ADDRESS}
billing.service.grpc.port=${BILLING_SERVICE_GRPC_PORT}

#Kafka
spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.consumer.group-id=patient-message
spring.kafka.consumer.auto-offset-reset=earliest

#Kafka producer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer
