
services:
  pms-service:
    build: pmsmodule
    container_name: patient-service-api
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patient_management_system
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: Dennis123
      SPRING_REDIS_HOST: redis
    networks:
      - pms-network

  billing-service:
      build: Billing-Service
      container_name: billing-service-api
      ports:
        - "4001:4001"
        - "9001:9001"
      depends_on:
        - pms-service
      networks:
        - pms-network


  postgres:
    image: postgres:16
    container_name: patient-service-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: patient_management_system
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Dennis123
    volumes:
      - ./pmsmodule/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - pms-network

  redis:
    image: redis:7.4.2
    container_name: patient-service-redis
    ports:
      - "6379:6379"
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge