
services:
  pms-service:
    build: pmsmodule
    container_name: patient-service-api
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_REDIS_HOST: redis
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    networks:
      - pms-network

  billing-service:
      build: Billing-Service
      container_name: billing-service-api
      ports:
        - "4001:4001"
        - "9001:9001"
      depends_on:
        - pms-service
      networks:
        - pms-network


  postgres:
    image: postgres:16
    container_name: patient-service-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: patient_management_system
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./pmsmodule/src/main/resources/data.sql:/docker-entrypoint-initdb.d/data.sql
    networks:
      - pms-network

  redis:
    image: redis:7.4.2
    container_name: patient-service-redis
    ports:
      - "6379:6379"
    networks:
      - pms-network

networks:
  pms-network:
    driver: bridge