server:
  port: 4004

spring:
  cloud:
    gateway:
      routes:
#        - id: auth-service-route
#          uri: http://auth-service:4005
#          predicates:
#            - Path=/auth/**
        - id: authentication-service-route
          uri: http:auth-service:4005
          predicates:
            - Path=/auth/**

        - id: patient-service-route
          uri: http://pms-service:4000
          predicates:
            - Path=/api/v1/patients/**


        - id: api-docs-patient-route
          uri: http://pms-service:4000
          predicates:
            - Path=/v3/api-docs


